server:
  port: 8080

---

spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json

logging:
  path: /logs/order
  file:
    max-history: 30
  level:
    org.springframework.cloud: debug


server:
  port: 8082
---

spring:
  profiles: docker
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json

logging:
  path: /logs/order
  file:
    max-history: 30
  level:
    org.springframework.cloud: debug